<!-- Bootstrap CSS -->
      <!-- Required meta tags -->
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Eigen CSS -->
  <link rel="stylesheet" href="./css/style.css">
  <link rel="stylesheet" href="./css/home.css">
  <link rel="stylesheet" href="./css/banner.css">
  <link rel="stylesheet" href="./css/forum.css">
  <link rel="stylesheet" href="./css/shop.css">
  <link rel="stylesheet" href="./css/cart.css">
  
  
   <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="./js/script.js"></script>